version: 0.0.2-{build}-{branch}
image:
- Ubuntu
- Visual Studio 2017

for:
-
  matrix:
    only: 
      - image: Ubuntu
  install:
  - sh: |
      git submodule init
      git submodule update --recursive
  build_script:
  - sh: make all
  test_script:
  - sh: make runtest

-
  matrix:
    only: 
      - image: Visual Studio 2017
  install:
  - ps: |
      git submodule init
      git submodule update --recursive
  build_script:
  - ps: |
      tree
      make all
      tree
  test_script:
  - ps: make runtest

artifacts:
- path: src/libts.a
  name: libts.a
- path: src/libts.so
  name: libts.so
- path: src/libts.dll
  name: libts.dll