
[x] ./tsys ls -i -t ...
[x] ./tsys mk --id --preview --silent ...
[ ] ./tsys rm --id --force --silent ...
[x] ./tsys tag --id --force ...
[x] ./tsys cs --silent ...
    -- sometimes, its possible to fuck the set parser. Not sure how. Something about not having spaces?
[x] ./tsys pws
